[ci skip] update .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,50 +1,52 @@
-image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.8.1
+include: https://api.choerodon.com.cn/devops/v1/projects/1529/ci_contents/pipelines/addc9c6b-40eb-46e7-ac25-c20c3b57d214/content.yaml
 
-stages:
-  - build
-  - release
-
-build:
-  stage: build
-  script:
-    - update_pom_version
-    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent  test -Dmaven.test.failure.ignore=true -DskipTests=false -U
-    - mvn --batch-mode  verify sonar:sonar  -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.analysis.serviceGroup=$GROUP_NAME -Dsonar.analysis.commitId=$CI_COMMIT_SHA -Dsonar.projectKey=${GROUP_NAME}:${PROJECT_NAME}
-    - mvn package spring-boot:repackage
-    - mv target/app.jar $PWD/docker
-    - kaniko -c $PWD/docker -f $PWD/docker/Dockerfile -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
-
-release:
-  stage: release
-  script:
-    - chart_build
-
-maven-deploy-snapshot:
-  stage: build
-  script:
-    - mvn clean install -Dmaven.springboot.skip=true -DskipTests=true deploy -DaltDeploymentRepository=${CHOERODON_SNAPSHOT_REPOSITORY_ID}::default::${CHOERODON_SNAPSHOT_URL} -Ddeploy.classifier=exec
-  # 只有master, release和hotfix分支才发包
-  only:
-    refs:
-    - master
-    - /^.*hotfix.*$/
-    - /^.*release.*$/
-
-maven-deploy-release:
-  stage: build
-  script:
-    - mvn clean install -Dmaven.springboot.skip=true -DskipTests=true deploy -DaltDeploymentRepository=${CHOERODON_RELEASE_REPOSITORY_ID}::default::${CHOERODON_RELEASE_URL} -Ddeploy.classifier=exec
-  only:
-    - tags
-
-
-.auto_devops: &auto_devops |
-  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
-  if [ "$http_status_code" != "200" ]; then
-    cat .auto_devops.sh
-    exit 1
-  fi
-  source .auto_devops.sh
-
-before_script:
-  - *auto_devops
+#image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.8.1
+#
+#stages:
+#  - build
+#  - release
+#
+#build:
+#  stage: build
+#  script:
+#    - update_pom_version
+#    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent  test -Dmaven.test.failure.ignore=true -DskipTests=false -U
+#    - mvn --batch-mode  verify sonar:sonar  -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.analysis.serviceGroup=$GROUP_NAME -Dsonar.analysis.commitId=$CI_COMMIT_SHA -Dsonar.projectKey=${GROUP_NAME}:${PROJECT_NAME}
+#    - mvn package spring-boot:repackage
+#    - mv target/app.jar $PWD/docker
+#    - kaniko -c $PWD/docker -f $PWD/docker/Dockerfile -d ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}
+#
+#release:
+#  stage: release
+#  script:
+#    - chart_build
+#
+#maven-deploy-snapshot:
+#  stage: build
+#  script:
+#    - mvn clean install -Dmaven.springboot.skip=true -DskipTests=true deploy -DaltDeploymentRepository=${CHOERODON_SNAPSHOT_REPOSITORY_ID}::default::${CHOERODON_SNAPSHOT_URL} -Ddeploy.classifier=exec
+#  # 只有master, release和hotfix分支才发包
+#  only:
+#    refs:
+#    - master
+#    - /^.*hotfix.*$/
+#    - /^.*release.*$/
+#
+#maven-deploy-release:
+#  stage: build
+#  script:
+#    - mvn clean install -Dmaven.springboot.skip=true -DskipTests=true deploy -DaltDeploymentRepository=${CHOERODON_RELEASE_REPOSITORY_ID}::default::${CHOERODON_RELEASE_URL} -Ddeploy.classifier=exec
+#  only:
+#    - tags
+#
+#
+#.auto_devops: &auto_devops |
+#  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
+#  if [ "$http_status_code" != "200" ]; then
+#    cat .auto_devops.sh
+#    exit 1
+#  fi
+#  source .auto_devops.sh
+#
+#before_script:
+#  - *auto_devops
